version: "2.3"

services:
  mtl:
    container_name: autogoal-mtl
    build:
      context: mtl-dockerfile
      dockerfile: mtl.dockerfile
    hostname: autogoal
    ports:
      - 8501:8501
      - 8000:8000
    volumes:
      - "./autogoal:/usr/lib/python3/dist-packages/autogoal"
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
#      - "./download_datasets:/home/coder/autogoal"
#       - "../datasets:/home/coder/.autogoal"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"
    command: ["python", "test.py", "download_datasets"]
